version: "3"

services:
  db:
    image: postgres:14
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_DB: rasporedar
      POSTGRES_USER: rasporedar
      POSTGRES_PASSWORD: rasporedar
    ports:
      - 3002:5432

  backend:
    build: ./backend
    container_name: be
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: rasporedar
      POSTGRES_USER: rasporedar
      POSTGRES_PASSWORD: rasporedar
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:?err}"
      SALT_ROUNDS: "${SALT_ROUNDS:?err}"
    healthcheck:
      test: curl -f localhost:3001/healthcheck/ping
      interval: 3s
    ports:
      - 3001:3001
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: fe
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
