#!/bin/sh

CMD=$1; shift

case "$CMD"  in
  -i|--install)
    (cd backend && yarn)
    (cd frontend && yarn)

    curl -O https://raw.githubusercontent.com/bdeak4/bin/master/compose
    chmod +x compose

    if [ ! -f .env ]; then
      cp .env.example .env
      echo Please insert variables in .env
    fi
    ;;

  -d|--dev)
    echo "Environment variables from .env files loaded"
    if [ -f .env ]; then
      export $(grep -v '^#' .env | xargs)
    fi

    ./compose \
      --frontend "yarn --cwd frontend dev" \
      --backend "yarn --cwd backend dev"
    ;;

  *)
    echo "error: unknown parameter passed \"$CMD\"";
    echo "usage: $0 [-i] [-d]"
    echo
    echo "  -i, --install            Install project dependencies"
    echo "  -d, --dev                Run project in development mode"
    echo
    ;;
esac
