import { GenerateScheduleProps } from './types';

export const generateScheduleProps: GenerateScheduleProps = {
  classes: [
    {
      name: '5a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Ante Antic' } },
      ],
    },
    {
      name: '5b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Iva Ivic' } },
      ],
    },
    {
      name: '5c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Tomislav Tomic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Maja Majic' } },
      ],
    },

    {
      name: '6a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Marko Markic' } },
      ],
    },
    {
      name: '6b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Mate Matic' } },
      ],
    },
    {
      name: '6c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: 'Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: 'Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Nikola Nikolic' } },
      ],
    },
    {
      name: '7a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: 'Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Nikolina Nikolinic' } },
      ],
    },
    {
      name: '7b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Mate Matic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: 'Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Marica Maric' } },
      ],
    },
    {
      name: '8a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: 'Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: 'Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
      ],
    },
    {
      name: '8b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: 'Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: 'Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Roko Rokic' } },
      ],
    },
    {
      name: '8c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: 'Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: 'Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: 'Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: 'Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: 'Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: 'Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: 'Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: 'Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: 'Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: 'Kreso Kresic' } },
        { name: 'Tjelesna i zdravstvena kultura', timesPerWeek: 2, teacher: { name: 'Mario Maric' }, classroom: { name: '001' } }, // prettier-ignore
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: 'Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: 'Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: 'Mislav Mislavic' } },
      ],
    },
  ],
  classrooms: [
    { name: '001' },
    { name: '100' },
    { name: '101' },
    { name: '102' },
    { name: '103' },
    { name: '104' },
    { name: '105' },
    { name: '106' },
    { name: '107' },
    { name: '108' },
    { name: '109' },
    { name: '110' },
    { name: '111' },
    { name: '201' },
    { name: '202' },
    { name: '203' },
    { name: '204' },
    { name: '205' },
    { name: '206' },
  ],
};
