import { GenerateTimetableProps } from './types';

export const generateTimetableProps: GenerateTimetableProps = {
  classes: [
    {
      name: '5a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 2, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '7 - Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '1 - Ante Antic' } },
      ],
    },
    {
      name: '5b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '12 - Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 2, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '7 - Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' } },
      ],
    },
    {
      name: '5c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 2, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '13 - Tomislav Tomic' } },
        { name: 'Priroda', timesPerWeek: 1, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '7 - Dino Dinic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' } },
      ],
    },

    {
      name: '6a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '12 - Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '4 - Marko Markic' } },
      ],
    },
    {
      name: '6b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '5 - Mate Matic' } },
      ],
    },
    {
      name: '6c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 5, teacher: { name: '12 - Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '4 - Marko Markic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Priroda', timesPerWeek: 2, teacher: { name: '6 - Nikola Nikolic' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '205' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '6 - Nikola Nikolic' } },
      ],
    },
    {
      name: '7a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '18 - Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '13 - Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: '16 - Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '16 - Nikolina Nikolinic' } },
      ],
    },
    {
      name: '7b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '18 - Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '5 - Mate Matic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: '16 - Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '17 - Marica Maric' } },
      ],
    },
    {
      name: '8a',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: '12 - Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '18 - Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '13 - Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: '16 - Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
      ],
    },
    {
      name: '8b',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: '1 - Ante Antic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '18 - Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '13 - Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: '16 - Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '10 - Roko Rokic' } },
      ],
    },
    {
      name: '8c',
      subjects: [
        { name: 'Hrvatski jezik', timesPerWeek: 4, teacher: { name: '12 - Ana Anic' } },
        { name: 'Likovna kultura', timesPerWeek: 1, teacher: { name: '2 - Iva Ivic' }, classroom: { name: '203' } },
        { name: 'Glazbena kultura', timesPerWeek: 1, teacher: { name: '3 - Maja Majic' }, classroom: { name: '204' } },
        { name: 'Engleski jezik', timesPerWeek: 3, teacher: { name: '18 - Marta Martic' } },
        { name: 'Matematika', timesPerWeek: 4, teacher: { name: '13 - Tomislav Tomic' } },
        { name: 'Biologija', timesPerWeek: 2, teacher: { name: '16 - Nikolina Nikolinic' } },
        { name: 'Kemija', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '201' } },
        { name: 'Fizika', timesPerWeek: 2, teacher: { name: '17 - Marica Maric' }, classroom: { name: '202' } },
        { name: 'Povijest', timesPerWeek: 2, teacher: { name: '14 - Mislav Mislavic' } },
        { name: 'Geografija', timesPerWeek: 2, teacher: { name: '8 - Luka Lukic' } },
        { name: 'Tehnička kultura', timesPerWeek: 1, teacher: { name: '9 - Kreso Kresic' } },
        { name: 'Tjelesni', timesPerWeek: 2, teacher: { name: '11 - Mario Maric' }, classroom: { name: '001' } },
        { name: 'Informatika', timesPerWeek: 2, teacher: { name: '10 - Roko Rokic' }, classroom: { name: '206' } },
        { name: 'Vjeronauk', timesPerWeek: 2, teacher: { name: '15 - Ankica Ankic' } },
        { name: 'Sat razrednika', timesPerWeek: 1, teacher: { name: '14 - Mislav Mislavic' } },
      ],
    },
  ],
  classrooms: [
    { name: '001' },
    { name: '100' },
    { name: '101' },
    { name: '102' },
    { name: '103' },
    { name: '104' },
    { name: '105' },
    { name: '106' },
    { name: '107' },
    { name: '108' },
    { name: '109' },
    { name: '110' },
    { name: '111' },
    { name: '201' },
    { name: '202' },
    { name: '203' },
    { name: '204' },
    { name: '205' },
    { name: '206' },
  ],
};
