name: Pull request
on:
  - pull_request

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - run: yarn
        working-directory: backend

      - run: yarn
        working-directory: frontend

      - name: Run linters on backend
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: backend
          eslint_extensions: ts
          prettier: true
          prettier_dir: backend
          prettier_extensions: ts

      - name: Run linters on frontend
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: frontend
          eslint_extensions: vue,js
          prettier: true
          prettier_dir: frontend
          prettier_extensions: vue,js

  pulumi_preview:
    name: Pulumi preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: yarn
        working-directory: deployment/infrastructure

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: deployment/infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
